### ISSUE TITLE
기능 요구사항

### ISSUE THREAD

**Issue by sihyun10** [sihyun10/hangman_game#1]
주어진 요구사항을 기반으로 기능을 잘 적용했는지 확인

##  Todo List

- [x] 문제를 선택할 수 있도록 영어 단어를 랜덤으로 3개 띄우기 (30개 이상의 단어들 중에서)
- [x] 선택한 문제의 단어를 글자 단위로 숨긴다. (ex. 'apple' => '_ _ _ _ _')
- [x] 화면에 26개의 알파벳을 띄워라.
- [x] 선택한 알파벳과 정답을 비교한다.
- [x] 일치하는 알파벳이 있을 경우, 기존 UI에서 사라지고 해당 위치에 표시되게끔 해라.
- [x] 틀릴 경우, 기존 위치에서 알파벳이 빨간색으로 바뀌고, 오류 횟수를 증가시킨다.
- [x] 오류 날때마다 **'교수대-밧줄-머리-팔-손-몸통-다리-발'** 순서로 그려서 그림이 완성되면 '실패를 띄운다. (오류 횟수 8번 이상 - 실패) 

## 지켜야할것

- [x] 선택한 알파벳과 정답을 비교해 일치하면은 그 알파벳이 있는 자리에 모두 나타나게끔 해야한다.
```
ex) 'HANGHAE' 
1) _ _ _ _ _ _ _ (밑줄 7개) 이 상태에서 H를 고르게되면
2) H _ _ _ H _ _ (H가 있는 자리에 모두 H가 드러나게된다)
```
- [x] 게임이 종료되면 정답을 표시해주고, 결과 메시지를 출력해줘야한다.
(성공 => 성공의 메시지, 실패 => 실패의 메시지)

## 추가적으로 해야할 부분

- [x] 배포하기

**Comment by sihyun10** [comment]
배포 확인할 점
- [x] 폰으로 봤을때 화면이 안깨지는지
- [x] 화면 크기는 적당한지
- [x] 반응속도가 느리진 않는지
- [x] 구현한 기능들이 잘 작동되는지

**Comment by sihyun10** [comment]
폰으로 확인했을때, 화면도 안깨지고, 화면 크기도 적당했다. 구현기능 또한 잘 작동하였다.
(재로딩(?) 화면이 로드될때 모달창이 잠시 비췄다가 없어지는 현상이 있었다)

![image](https://github.com/sihyun10/hangman_game/assets/92582664/506aaa86-b5a5-4268-be19-605767de5e9a)

![image](https://github.com/sihyun10/hangman_game/assets/92582664/0bf1a901-d14c-4782-9bfe-d37307c61477)
